<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TbTamiuDesaAdatTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tb_tamiu_desa_adat')->delete();
        
        \DB::table('tb_tamiu_desa_adat')->insert(array (
            0 => 
            array (
                'id' => 1,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4716748930057915',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:11',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '5230227651166837',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4916225907162836',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4485095158608766',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '348425385051172',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '5107656656043304',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '2351081795444364',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '5513797846363703',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4024007103498563',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '2221363412874266',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '2452659908382932',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4916323699824356',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '2720198965387746',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4024007154118425',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:14',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '2648062684015161',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:14',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '2406672341292326',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:14',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '374600687606850',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:14',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '6011210935726306',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:14',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4485623788691',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4716446690981',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '2221776297894440',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4024007108124024',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '6011268664122485',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '4485087366194960',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'banjar_adat_id' => NULL,
                'banjar_dinas_id' => NULL,
                'nomor_tamiu' => '6011129805699544',
                'tanggal_masuk' => NULL,
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => NULL,
                'created_at' => '2021-10-21 11:34:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'banjar_adat_id' => 1,
                'banjar_dinas_id' => 10,
                'nomor_tamiu' => '030701103130600001',
                'tanggal_masuk' => '2022-01-18',
                'tanggal_keluar' => NULL,
                'penduduk_id' => 3,
                'wna_id' => NULL,
                'created_at' => '2022-01-21 09:39:50',
                'updated_at' => '2022-01-21 02:39:50',
                'deleted_at' => '2022-01-21 02:39:50',
            ),
            26 => 
            array (
                'id' => 27,
                'banjar_adat_id' => 1,
                'banjar_dinas_id' => 10,
                'nomor_tamiu' => '030702103200122001',
                'tanggal_masuk' => '2020-01-15',
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => 1,
                'created_at' => '2022-01-21 11:53:28',
                'updated_at' => '2022-01-21 04:53:27',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'banjar_adat_id' => 1,
                'banjar_dinas_id' => 10,
                'nomor_tamiu' => '030701103200122001',
                'tanggal_masuk' => '2022-01-18',
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => 2,
                'created_at' => '2022-01-20 11:20:24',
                'updated_at' => '2022-01-20 11:20:24',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'banjar_adat_id' => 1,
                'banjar_dinas_id' => 10,
                'nomor_tamiu' => '030701103131000001',
                'tanggal_masuk' => '2000-10-13',
                'tanggal_keluar' => NULL,
                'penduduk_id' => 2,
                'wna_id' => NULL,
                'created_at' => '2022-01-21 10:27:22',
                'updated_at' => '2022-01-21 03:27:21',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'banjar_adat_id' => 1,
                'banjar_dinas_id' => 10,
                'nomor_tamiu' => '030701103170122001',
                'tanggal_masuk' => '2022-01-19',
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => 4,
                'created_at' => '2022-01-21 09:41:57',
                'updated_at' => '2022-01-21 02:41:57',
                'deleted_at' => '2022-01-21 02:41:57',
            ),
            30 => 
            array (
                'id' => 32,
                'banjar_adat_id' => 2,
                'banjar_dinas_id' => 10,
                'nomor_tamiu' => '030702103130600001',
                'tanggal_masuk' => '2022-01-11',
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => 5,
                'created_at' => '2022-01-21 02:03:48',
                'updated_at' => '2022-01-21 02:03:48',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'banjar_adat_id' => 10,
                'banjar_dinas_id' => 13,
                'nomor_tamiu' => '03250203130779001',
                'tanggal_masuk' => '2022-01-01',
                'tanggal_keluar' => NULL,
                'penduduk_id' => 39,
                'wna_id' => NULL,
                'created_at' => '2022-01-25 20:52:41',
                'updated_at' => '2022-01-25 20:52:41',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'banjar_adat_id' => 9,
                'banjar_dinas_id' => 12,
                'nomor_tamiu' => '003250103200122001',
                'tanggal_masuk' => '2022-01-01',
                'tanggal_keluar' => NULL,
                'penduduk_id' => NULL,
                'wna_id' => 1,
                'created_at' => '2022-01-25 20:55:38',
                'updated_at' => '2022-01-25 20:55:38',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 35,
                'banjar_adat_id' => 9,
                'banjar_dinas_id' => 12,
                'nomor_tamiu' => '03250103130600001',
                'tanggal_masuk' => '2022-01-02',
                'tanggal_keluar' => NULL,
                'penduduk_id' => 30,
                'wna_id' => NULL,
                'created_at' => '2022-01-31 08:57:04',
                'updated_at' => '2022-01-31 08:57:04',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 36,
                'banjar_adat_id' => 9,
                'banjar_dinas_id' => 12,
                'nomor_tamiu' => '03250103130101001',
                'tanggal_masuk' => '2020-01-13',
                'tanggal_keluar' => NULL,
                'penduduk_id' => 44,
                'wna_id' => NULL,
                'created_at' => '2022-01-31 09:05:01',
                'updated_at' => '2022-01-31 09:05:01',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}